springboot-deployment:
  app:
    name: sbm-declaration-services
    env:
      java:
        args: -Xms2g -Xmx2g
      springboot:
        profile: sc-test
        sysType: SC-TEST
    resources:
      limits:
        cpu: '2'
        memory: 3Gi
      requests:
        cpu: '0.5'
        memory: 3Gi
    autoscale:
      minReplicas: 1
      maxReplicas: 1
    service:
      port: 8080
      contextPath: /sbm-declaration-services
    probes:
      liveness: /sbm-declaration-services/actuator/health/liveness
      readiness: /sbm-declaration-services/actuator/health/readiness

# Names of the ConfigMaps rendered by the templates in this chart.
configMap:
  commonName: sbm-declaration-services-common-config
  name: sbm-declaration-services-config

secret:
  name: sbm-declaration-services-secret
