global:
  overrides:
    esb:
      # null = use the default in chart/configs/application-prod.yml.
      server: ~

springboot-deployment:
  app:
    env:
      java:
        args: -Xms4g -Xmx4g -XX:+FlightRecorder
      springboot:
        profile: prod
        sysType: PROD
    resources:
      limits:
        cpu: '2'
        memory: 6Gi
      requests:
        cpu: '1'
        memory: 6Gi
    secretManager:
      vault:
        secret: kv/data/PROD
        template: |
          {{ with secret "kv/data/PROD/data-source/opusAgencyDataSource" -}}
            export SPRING_DATASOURCE_USERNAME="{{ .Data.data.username }}"
            export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.password }}"
            export SPRING_DATASOURCE_URL="{{ .Data.data.url }}"
          {{- end }}
    autoscale:
      minReplicas: 1
      maxReplicas: 5
