---------------------------------------------------------------------
-- SBM YSV BEYANNAME — SENARYO TEST VERİSİ
-- sample_data_scenarios.sql
-- Açıklama: Her kod yolunu tetikleyen KÜÇÜK ve ETİKETLİ veri seti.
--   (Toplu/gerçekçi hacim için db/sample_insert.sql — 50 satır — ayrı durur.)
--
--   Tablo adları ŞEMA ÖNEKSİZ: lokalde kendi şemanda, prod/SC-TEST'te public
--   synonym üzerinden çalışır.
--
--   Grup anahtarı = (DECLARATION_YEAR, DECLARATION_MONTH, CITY_CODE, DISTRICT_CODE).
--   ysvDosyaNo anahtarın parçası DEĞİLDİR; grubun satırlarından okunur.
--   Büyükşehir satırlarında DISTRICT_CODE = 0 -> uygulama ilceKodu göndermez.
--   COMPANY_CODE daima '045'.
--
-- KULLANIM: setup_db.sql (veya local/local_setup.sql) sonrası bir kez çalıştır.
--   Tekrar yüklemeden önce:  DELETE FROM ALZ_SBM_DECL_LOG;
--                            DELETE FROM ALZ_SBM_DECL_PROCESS WHERE SBM_FILE_NO LIKE 'YSV-T-%';
---------------------------------------------------------------------

-- =====================================================================
-- Belediye referansı (birkaç örnek — ilçeli senaryolar için)
-- =====================================================================
INSERT INTO ALZ_SBM_MUNICIPALITY (CITY_CODE, DISTRICT_CODE, MUNICIPALITY_NAME, EMAIL, NOTIFICATION_TYPE)
  VALUES (22, 2201, 'Edirne Merkez Belediyesi', 'edirne@ornek.bel.tr', 'BOTH');
INSERT INTO ALZ_SBM_MUNICIPALITY (CITY_CODE, DISTRICT_CODE, MUNICIPALITY_NAME, EMAIL, NOTIFICATION_TYPE)
  VALUES (22, 2202, 'Kesan Belediyesi', 'kesan@ornek.bel.tr', 'KEP');

-- =====================================================================
-- S1 — Büyükşehir, TEK MENKUL satır, STATUS=NEW
--      Beklenti: send -> POST, ilceKodu payload'da YOK, ysvTutarList 1 eleman
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 34, 0, '045', DATE '2026-08-31', 'YSV-T-0001',
  1000.00, 0.00, NULL, 'MENKUL', 100.00, 10, 1000.00, 'NEW', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S2 — Büyükşehir OLMAYAN il, TEK GAYRIMENKUL satır, ilçe DOLU, STATUS=NEW
--      Beklenti: send -> POST, ilceKodu=2201 gönderilir
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 22, 2201, '045', DATE '2026-08-31', 'YSV-T-0002',
  4472.90, 1.10, NULL, 'GAYRIMENKUL', 447.18, 10, 4471.80, 'NEW', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S3 — KOMPLEKS: AYNI grup, MENKUL + GAYRIMENKUL 2 satır, STATUS=NEW
--      GAYRIMENKUL satırında NEGATİF gecmisAyIadeTutari
--      Beklenti: send -> POST, ysvTutarList 2 eleman; biri gecmisAyIadeTutari = -1500.75
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 6, 0, '045', DATE '2026-08-31', 'YSV-T-0003',
  1818311.26, 67993.54, NULL, 'MENKUL', 175031.77, 10, 1750317.72, 'NEW', 'SEED', 'senaryo.xlsx');
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 6, 0, '045', DATE '2026-08-31', 'YSV-T-0003',
  1069941.33, 43293.72, -1500.75, 'GAYRIMENKUL', 102664.76, 10, 1026647.61, 'NEW', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S4 — GÜNCELLEME senaryosu: AYNI grup, MENKUL + GAYRIMENKUL, STATUS=SENT, ay=7
--      Beklenti: update -> PUT (ay/yil/ilKodu/ilceKodu YOK); cancel -> tutarlar 0 PUT
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, DATE_SENT, SENT_BY_USER, SOURCE_FILE_NAME)
 VALUES (7, 2026, 35, 0, '045', DATE '2026-07-31', 'YSV-T-0004',
  531307.03, 94386.74, NULL, 'MENKUL', 43692.03, 10, 436920.29, 'SENT', 'SEED', DATE '2026-07-15', 'SEED', 'senaryo.xlsx');
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, DATE_SENT, SENT_BY_USER, SOURCE_FILE_NAME)
 VALUES (7, 2026, 35, 0, '045', DATE '2026-07-31', 'YSV-T-0004',
  468428.35, 39826.17, -500.00, 'GAYRIMENKUL', 42860.22, 10, 428602.18, 'SENT', 'SEED', DATE '2026-07-15', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S5 — SORGU + COMPLETED senaryosu: 2 satır, STATUS=COMPLETED
--      Beklenti: query(YSV-T-0005) -> SBM'den data döner; ilgili satırlar zaten COMPLETED
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, DATE_SENT, SENT_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 16, 0, '045', DATE '2026-08-31', 'YSV-T-0005',
  15985674.25, 51612.96, NULL, 'MENKUL', 1593406.13, 10, 15934061.29, 'COMPLETED', 'SEED', DATE '2026-08-10', 'SEED', 'senaryo.xlsx');
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, DATE_SENT, SENT_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 16, 0, '045', DATE '2026-08-31', 'YSV-T-0005',
  8307578.66, 19013.07, NULL, 'GAYRIMENKUL', 828856.56, 10, 8288565.59, 'COMPLETED', 'SEED', DATE '2026-08-10', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S6 — HATA / RETRY senaryosu: TEK MENKUL satır, STATUS=ERROR, ERROR_DETAILS dolu
--      Beklenti: send tekrar dener (ERROR -> SENDABLE)
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, ERROR_DETAILS, DATE_UPDATED, UPDATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 7, 0, '045', DATE '2026-08-31', 'YSV-T-0006',
  60856.33, 833.90, NULL, 'MENKUL', 6002.24, 10, 60022.43, 'ERROR', 'SEED',
  'SEC-00002: Token gecersiz veya suresi dolmus.', DATE '2026-08-20', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S7 — MÜKERRER MENKUL TİPİ (yerel RISK-HAVUZU-00005 guard): AYNI grupta 2 satır İKİSİ DE MENKUL
--      Beklenti: SbmMapper.toAmountList RISK-HAVUZU-00005 fırlatır; grup ERROR olur, SBM'ye gitmez
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 42, 0, '045', DATE '2026-08-31', 'YSV-T-0007',
  100.00, 0.00, NULL, 'MENKUL', 10.00, 10, 100.00, 'NEW', 'SEED', 'senaryo.xlsx');
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 42, 0, '045', DATE '2026-08-31', 'YSV-T-0007',
  200.00, 0.00, NULL, 'MENKUL', 20.00, 10, 200.00, 'NEW', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S8 — OPUS ANOMALİSİ: AYNI grup, FARKLI ysvDosyaNo (2 satır), STATUS=NEW
--      Beklenti: SbmMapper.resolveFileNo ilkini kullanır + log.warn; gönderim durmaz
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 1, 0, '045', DATE '2026-08-31', 'YSV-T-0008A',
  500.00, 0.00, NULL, 'MENKUL', 50.00, 10, 500.00, 'NEW', 'SEED', 'senaryo.xlsx');
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 1, 0, '045', DATE '2026-08-31', 'YSV-T-0008B',
  600.00, 0.00, NULL, 'GAYRIMENKUL', 60.00, 10, 600.00, 'NEW', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S9 — PROCESSING'de takılı kalmış (crash sonrası kurtarma) — TEK satır
--      Beklenti: send/update ALMAZ (SENDABLE/UPDATABLE değil) -> status conflict raporlanır
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 33, 0, '045', DATE '2026-08-31', 'YSV-T-0009',
  777.00, 0.00, NULL, 'MENKUL', 77.70, 10, 777.00, 'PROCESSING', 'SEED', 'senaryo.xlsx');

-- =====================================================================
-- S10 — Tüm tutarlar 0 (cancel sonrası benzeri), STATUS=NEW, TEK GAYRIMENKUL
-- =====================================================================
INSERT INTO ALZ_SBM_DECL_PROCESS
 (DECLARATION_MONTH, DECLARATION_YEAR, CITY_CODE, DISTRICT_CODE, COMPANY_CODE, PAYMENT_DATE, SBM_FILE_NO,
  RECEIVED_PREMIUM_AMOUNT, CANCELLED_PREMIUM_AMOUNT, PREV_MONTH_REFUND_AMOUNT, MOVABLE_TYPE,
  TAX_AMOUNT, TAX_RATIO, TAX_PREMIUM_AMOUNT, STATUS, CREATED_BY_USER, SOURCE_FILE_NAME)
 VALUES (8, 2026, 31, 0, '045', DATE '2026-08-31', 'YSV-T-0010',
  0.00, 0.00, 0.00, 'GAYRIMENKUL', 0.00, 10, 0.00, 'NEW', 'SEED', 'senaryo.xlsx');

COMMIT;

---------------------------------------------------------------------
-- Senaryo özeti:
--   SELECT SBM_FILE_NO, STATUS, DECLARATION_YEAR, DECLARATION_MONTH,
--          CITY_CODE, DISTRICT_CODE, MOVABLE_TYPE, PREV_MONTH_REFUND_AMOUNT
--     FROM ALZ_SBM_DECL_PROCESS
--    WHERE SBM_FILE_NO LIKE 'YSV-T-%'
--    ORDER BY SBM_FILE_NO, MOVABLE_TYPE;
---------------------------------------------------------------------
